### ISSUE TITLE
Party Movement Bugs

### ISSUE THREAD

**Issue by jhmullen** [jhmullen/feast-react#22]
Tested using player 1 only

- Guests cannot be moved to the right using RightArrow

- Guests cannot be added after initial guest, failing with `table.filter is not a function`.

**Comment by bbqbaron** [comment]
Does email reply to issues work? Anyway, gross, sorry. Will have this, #23,
#24 fixed with the extra tests I've been neglecting this weekend.

Tangent: how do you feel about an incrementally adoptable type system like
Flow? It would have caught about 85% of the boneheaded errors I've
introduced. Still good to have tests, but it's nice not to need them for
"Are you not stupid" and just write them for behavioral assertions. Speeds
up reactors like this a ton in my experience.

**Comment by jhmullen** [comment]
Yes!  Email reply seems to work.  As you may have picked up, my programming experience and style is far more "shoot from the hip," in that I've not written test suites before (even Jest is new to me!) and have been like committing straight to master haha.

That said, I have no qualms with introducing a type system, as part of reason behind this side project is to expand my experience with programming best practices and open source workflow.  

Flow away!

**Comment by jhmullen** [comment]
Regarding style, I am definitely finding myself struggling with the more functional programming style, as my background is mainly imperative.  I'm looking at this particular issue myself and it's definitely taking me longer to grok the new code with nested/wrapped functions and reducers.  So please forgive me if my bug fixes or master commits are more old-fashioned / imperative in style, I'm not trying to step on the cleanness, rather just working with what I know!

The partyPool reduce in MOVE_PARTY is slick as hell though ;)
