### ISSUE TITLE
Scripting?

### ISSUE THREAD

**Issue by bbqbaron** [jhmullen/feast-react#6]
This is kind of a discussion issue but could also be used to provide a single test case: when a card has rules (`When played does blah etc`), what do we do? Presumably we can't import this kind of thing from a CSV without creating our own DSL/`eval`-ing JS strings?

**Comment by bbqbaron** [comment]
Maybe some common abilities (trash a card) can be stored in card data and weird ones need scripting? For John's MVP card list, maybe I'm overthinking it and we just hardcode everything.

**Comment by jhmullen** [comment]
I had this same thought myself.  How do we script the weirder interactions?  

I ended up punting on the issue entirely. I figured I'd try to get the movement of cards between zones down so we can test as fast as possible, even if that means us manually enacting the stranger rules (For example. I considered adding a like, "neutral zone," or kind of disembodied collection, just so that weirder cards could float there or remind us of odder states).

I think a small set of common abilities is the best approach.  This was my thought with the "*_mod" columns in the CSV.  This could eventually have some abilities, not eval'd scripts, just keyworded interactions.  The rest I am thinking indeed will just be hard coded.
